<a href="https://colab.research.google.com/github/afr0thunder/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/oo_pytorch_fundamentals/

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3,], [3, 6, 9,], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start wit htensors full of random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5416, 0.8727, 0.8123, 0.6106],
        [0.1558, 0.6459, 0.7669, 0.0490],
        [0.5130, 0.1470, 0.9883, 0.8898]])

In [ ]:
# Create a random tensor with similar shapr to an image tensor
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.6761, 0.8995, 0.0535],
          [0.2980, 0.1574, 0.4421],
          [0.9263, 0.5611, 0.2753],
          ...,
          [0.1892, 0.8538, 0.4665],
          [0.9878, 0.5482, 0.5695],
          [0.0056, 0.7139, 0.9983]],
 
         [[0.2815, 0.1958, 0.9213],
          [0.7537, 0.5576, 0.5143],
          [0.9938, 0.6280, 0.7012],
          ...,
          [0.5094, 0.9189, 0.5778],
          [0.6753, 0.8330, 0.2673],
          [0.4677, 0.2630, 0.5808]],
 
         [[0.1424, 0.7939, 0.6212],
          [0.9794, 0.6983, 0.0640],
          [0.3713, 0.3979, 0.5751],
          ...,
          [0.6267, 0.2568, 0.4986],
          [0.7099, 0.3868, 0.3442],
          [0.6172, 0.4569, 0.0757]],
 
         ...,
 
         [[0.7078, 0.1002, 0.2188],
          [0.2546, 0.2115, 0.8904],
          [0.0770, 0.1419, 0.8404],
          ...,
          [0.1762, 0.5752, 0.6208],
          [0.3101, 0.4139, 0.7265],
          [0.3379, 0.1660, 0.5216]],
 
         [[0.0084, 0.1017, 0.5329],
          [0

## Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all one
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.range()
BOX = torch.arange(0, 1000, step=77)
BOX

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Create tensors like
BOX_ZEROS = torch.zeros_like(input=BOX)
BOX_ZEROS

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

Most common issues
1. Tesnors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor, represents precision and memory
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

In [ ]:
# Create a tensor
sometensor = torch.rand(3, 4)

In [ ]:
# Find out details
print(sometensor)
print(f"Datatype; {sometensor.dtype}")
print(f"Shape: {sometensor.shape}")
print(f'Device: {sometensor.device}')


tensor([[0.2710, 0.3442, 0.2175, 0.9967],
        [0.8344, 0.1033, 0.8386, 0.5438],
        [0.4067, 0.9111, 0.6357, 0.6976]])
Datatype; torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tesnsor by 10
tensor *10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication (dot product)

> Two main rules
* Inner dimesions need to match
* The resulting matrix has the shape of the outer dimesions

In [ ]:
# Element wise
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Dot Product
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

In [ ]:
# Transpose

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

## Tensor Aggregation:

finding min, max, mean, sum, etc.

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x.type(torch.float)), x.type(torch.float).mean()

(tensor(45.), tensor(45.))

## Finding the positional min and max

In [ ]:
# Index values
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View -
* Stacking -
* Squeezing - Removes one dimesnion
* Unsqueezing - Adds one dimention
* Permute -

In [ ]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimesion
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

## Indexing

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computer library

In [ ]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # PyTorch reflects float64 unless otherwise specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tesnor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

## Reproducability

use random seed, need to call for every block of code

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

## Running tensors and PyTorch objects on GPUs

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'